apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.name }}-vsvc
spec:
  gateways:
    - {{ .Values.name }}-gateway
  hosts:
    - {{ .Values.name }}.local
  http:
    - name: primary
      route:
        - destination:
            host: {{ .Values.name }}-active
          weight: 100
        - destination:
            host: {{ .Values.name }}-preview
          weight: 0