apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        istio-injection: enabled
    spec:
      containers:
      - name: {{ .Values.name }}
        image: argoproj/rollouts-demo:{{ .Values.version }}
        resources:
          requests:
            cpu: 200m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 1Gi
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
  strategy:
    canary:
      steps:
      {{- $duration := .Values.durationValue | float64 -}}
      {{- $durationValue := printf "%f%s" $duration .Values.durationUnit -}}
      {{- $setWeight := .Values.setWeight | int -}}
      {{- $count  := $setWeight | div 100 | int | sub 1 | int -}}
      {{- range $i ,$e := until $count }}
      - setWeight: {{ $i | add 1 | mul $setWeight | int }}
      - pause:
          duration: "{{ $durationValue }}"
      {{- end }}
      canaryService: "{{ .Values.name }}-preview" # required
      stableService: "{{ .Values.name }}-active"  # required
      maxSurge: "20%"
      trafficRouting:
        istio:
           virtualService: 
            name: "{{ .Values.name }}-vsvc"  # required
            routes:
            - primary # At least one route is required