apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-rollout-example
spec:
  maxReplicas: 20
  minReplicas: 2
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: {{ .Values.name }}
  targetCPUUtilizationPercentage: 80
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        istio-injection: enabled
    spec:
      containers:
      - name: {{ .Values.name }}
        image: argoproj/rollouts-demo:{{ .Values.version }}
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
  strategy:
    canary:
      steps: 
      {{- range until (div 100 .Values.durationValue) }}
      - {{ setWeight: . }}
      - {{ duration: {{ .Values.durationValue }}{{ .Values.durationUnit }} }}
      {{- end }}
      # - setWeight: 20
      # - pause:
      #     duration: {{ .Values.durationValue }}{{ .Values.durationUnit }}
      # - setWeight: 40
      # - pause:
      #     duration: {{ .Values.durationValue }}{{ .Values.durationUnit }}
      # - setWeight: 60
      # - pause:
      #     duration: {{ .Values.durationValue }}{{ .Values.durationUnit }}
      # - setWeight: 80
      # - pause:
      #     duration: {{ .Values.durationValue }}{{ .Values.durationUnit }}
      canaryService: "{{ .Values.name }}-preview" # required
      stableService: "{{ .Values.name }}-active"  # required
      maxSurge: "20%"
      trafficRouting:
        istio:
           virtualService: 
            name: "{{ .Values.name }}-vsvc"  # required
            routes:
            - primary # At least one route is required