apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: rollout-vsvc
spec:
  gateways:
    - rollout-gateway
  hosts:
    - rollout.local
  http:
    - name: primary
      route:
        - destination:
            host: {{ .Values.name }}-active
          weight: 100
        - destination:
            host: {{ .Values.name }}-preview
          weight: 0