apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: rollouts-demo
  template:
    metadata:
      labels:
        app: rollouts-demo
        istio-injection: enabled
    spec:
      nodeSelector:
        kubernetes.io/hostname: argo-worker-01
      containers:
      - name: rollouts-demo
        image: argoproj/rollouts-demo:{{ .Values.version }}
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          requests:
            cpu: 200m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 1Gi
  strategy:
    canary:
      steps:
      {{- $duration := .Values.durationValue | int -}}
      {{- $durationValue := printf "%d%s" $duration .Values.durationUnit -}}
      {{- $setWeight := .Values.setWeight | int -}}
      {{- $count  := $setWeight | div 100 | int | sub 1 | int -}}
      {{- range $i ,$e := until $count }}
      - setWeight: {{ $i | add 1 | mul $setWeight | int }}
      - pause:
          duration: "{{ $durationValue }}"
      {{- end }}
      canaryService: "rollouts-demo-preview" # required
      stableService: "rollouts-demo-active"  # required
      maxSurge: "20%"
      trafficRouting:
        istio:
           virtualService: 
            name: "rollouts-demo-vsvc"  # required
            routes:
            - primary # At least one route is required
