apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: rollouts-demo-vsvc
spec:
  gateways:
    - rollouts-demo-gateway
  hosts:
    - "*" #- istio-rollout.dev.argoproj.io
  http:
    - name: primary
      route:
        - destination:
            host: rollouts-demo-active
          weight: 100
        - destination:
            host: rollouts-demo-preview
          weight: 0