apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: argoproj/rollouts-demo:{{ .Values.version }}
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
  strategy:
    canary:
      steps:
      - setWeight: 5
      - pause:
          duration: 10m
      canaryService: {{ .Values.name }}-preview # required
      stableService: {{ .Values.name }}-active  # required
      trafficRouting:
        istio:
           virtualService: 
            name: service-active  # required
            routes:
            - primary # At least one route is required