apiVersion: v1
kind: Service
metadata:
  name: rollouts-demo-active
spec:
  type: NodePort
  selector:
    app: rollouts-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: {{ .Values.nodePortActive }}
  