apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-preview
spec:
  type: NodePort
  selector:
    app: {{ .Values.name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7000
      nodePort: {{ .Values.nodePortPreview }}
  
