apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-active
spec:
  type: NodePort
  selector:
    app: {{ .Values.name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: {{ .Values.nodePortActive }}
