apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollouts-demo
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: rollouts-demo
  template:
    metadata:
      labels:
        app: rollouts-demo
    spec:
      containers:
      - name: rollouts-demo
        image: paulbouwer/hello-kubernetes:{{ .Values.version }}
        ports:
        - containerPort: 8080